---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: El primer mensaje enviado
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La primer respuesta
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La llave de cifrado
  checked: true
name: Correte del medio
