---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La tabla con emojis y letras
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La botonera de emojis
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La cantidad de lugares que nos desplazamos en el abecedario
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: El código del cifrado César
  checked: false
name: Perfecta simetría
