---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: un programa que llena mi computadora de publicidades
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: un programa que espía mis actividades en Internet
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: un programa que no me deja acceder a mis archivos
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: un programa que hace que mi computadora funcione lenta
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: todas las anteriores
  checked: true
name: Cada malware por su nombre
